version: "3"

services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "for_bot"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    network_mode: host

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  poller:
    container_name: poller_container
    build:
      context: ./poller
    ports:
      - "9080:9080"
    depends_on:
      - db
      - rabbitmq
    command: bash -c "python main.py"
    network_mode: host

  bot:
    container_name: bot_container
    build:
      context: ./bot
    ports:
      - "9090:9090"
    depends_on:
      - db
      - rabbitmq
    command: bash -c "alembic upgrade head && python main.py"
    network_mode: host

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    network_mode: host
    depends_on:
      - db

volumes:
  pg_volume:
  pgadmin_volume:
