
version: "3"

services:
  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "for_bot"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    ports:
      - "5552:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    ports:
      - "15772:15672"
      - "5772:5672"

  poller:
    container_name: poller_container
    build:
      context: ./poller
    ports:
      - "9080:9080"
    depends_on:
      - db
      - rabbitmq
    links:
      - rabbitmq
    command: bash -c "python main.py"

  bot:
    container_name: bot_container
    build:
      context: ./bot
    ports:
      - "9090:9090"
    depends_on:
      - db
      - rabbitmq
    links:
      - rabbitmq
      - db
    command: bash -c "alembic upgrade head && python main.py"

volumes:
  pg_volume: