"""some renaming 2

Revision ID: 0614a347ab6c
Revises: df2732281e94
Create Date: 2022-09-11 17:26:41.160779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0614a347ab6c'
down_revision = 'df2732281e94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_players_sessions', sa.Column('session_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('association_players_sessions_sessions_id_fkey', 'association_players_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'association_players_sessions', 'game_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('association_players_sessions', 'sessions_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_players_sessions', sa.Column('sessions_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'association_players_sessions', type_='foreignkey')
    op.create_foreign_key('association_players_sessions_sessions_id_fkey', 'association_players_sessions', 'game_sessions', ['sessions_id'], ['id'], ondelete='CASCADE')
    op.drop_column('association_players_sessions', 'session_id')
    # ### end Alembic commands ###
