"""ended -> nullable

Revision ID: 828041b5f6bc
Revises: 95d6dbf5252f
Create Date: 2022-09-11 03:13:58.752966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828041b5f6bc'
down_revision = '95d6dbf5252f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_states', 'ended',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_states', 'ended',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
