"""Added ended column

Revision ID: 95d6dbf5252f
Revises: 37ca15cb4fd6
Create Date: 2022-09-11 03:08:25.860673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d6dbf5252f'
down_revision = '37ca15cb4fd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_states', sa.Column('ended', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_states', 'ended')
    # ### end Alembic commands ###
