"""add association_players_sessions with points column

Revision ID: df2732281e94
Revises: e02c8bf1ed14
Create Date: 2022-09-11 17:22:43.715655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2732281e94'
down_revision = 'e02c8bf1ed14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_players_sessions',
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('sessions_id', sa.BigInteger(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessions_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'sessions_id')
    )
    op.create_table('association_sessions_questions',
    sa.Column('session_state_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_state_id'], ['session_states.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_state_id', 'question_id')
    )
    op.drop_table('players_sessions')
    op.drop_table('sessions_questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_questions',
    sa.Column('session_state_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_answered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='sessions_questions_question_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_state_id'], ['session_states.session_id'], name='sessions_questions_session_state_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_state_id', 'question_id', name='sessions_questions_pkey')
    )
    op.create_table('players_sessions',
    sa.Column('player_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sessions_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='players_sessions_player_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessions_id'], ['game_sessions.id'], name='players_sessions_sessions_id_fkey', ondelete='CASCADE')
    )
    op.drop_table('association_sessions_questions')
    op.drop_table('association_players_sessions')
    # ### end Alembic commands ###
