"""some renaming

Revision ID: e02c8bf1ed14
Revises: 828041b5f6bc
Create Date: 2022-09-11 04:23:04.072424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02c8bf1ed14'
down_revision = '828041b5f6bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_sessions', sa.Column('player_id', sa.BigInteger(), nullable=True))
    op.add_column('players_sessions', sa.Column('sessions_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('players_sessions_players_fkey', 'players_sessions', type_='foreignkey')
    op.drop_constraint('players_sessions_game_sessions_fkey', 'players_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'players_sessions', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'players_sessions', 'game_sessions', ['sessions_id'], ['id'], ondelete='CASCADE')
    op.drop_column('players_sessions', 'game_sessions')
    op.drop_column('players_sessions', 'players')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players_sessions', sa.Column('players', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('players_sessions', sa.Column('game_sessions', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players_sessions', type_='foreignkey')
    op.drop_constraint(None, 'players_sessions', type_='foreignkey')
    op.create_foreign_key('players_sessions_game_sessions_fkey', 'players_sessions', 'game_sessions', ['game_sessions'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('players_sessions_players_fkey', 'players_sessions', 'players', ['players'], ['id'], ondelete='CASCADE')
    op.drop_column('players_sessions', 'sessions_id')
    op.drop_column('players_sessions', 'player_id')
    # ### end Alembic commands ###
