"""added timesettings

Revision ID: 37d24c44dbf0
Revises: d53cfb49b376
Create Date: 2023-03-12 05:05:00.391852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37d24c44dbf0"
down_revision = "d53cfb49b376"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "time_settings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("wait_word_time", sa.BigInteger(), nullable=False),
        sa.Column("wait_vote_time", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "game_rules", sa.Column("short_on_time", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "game_rules", sa.Column("req_vote_percentage", sa.Float(), nullable=False)
    )
    op.add_column(
        "game_rules", sa.Column("time_settings_id", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "game_rules",
        "time_settings",
        ["time_settings_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game_rules", type_="foreignkey")
    op.drop_column("game_rules", "time_settings_id")
    op.drop_column("game_rules", "req_vote_percentage")
    op.drop_column("game_rules", "short_on_time")
    op.drop_table("time_settings")
    # ### end Alembic commands ###
