"""added min max players rules

Revision ID: bf333f4b742e
Revises: e09ac18ab241
Create Date: 2023-03-20 17:32:23.825444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf333f4b742e'
down_revision = 'e09ac18ab241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rules', sa.Column('min_players', sa.BigInteger(), nullable=False))
    op.add_column('game_rules', sa.Column('max_players', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_rules', 'max_players')
    op.drop_column('game_rules', 'min_players')
    # ### end Alembic commands ###
