"""added lives to gamerules

Revision ID: e09ac18ab241
Revises: 37d24c44dbf0
Create Date: 2023-03-12 16:18:07.357846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09ac18ab241'
down_revision = '37d24c44dbf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association_players_sessions', sa.Column('lives', sa.Integer(), nullable=False))
    op.add_column('game_rules', sa.Column('lives', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_rules', 'lives')
    op.drop_column('association_players_sessions', 'lives')
    # ### end Alembic commands ###
