session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
database:
  host: localhost
  port: 5432
  user: postgres
  password: 17
  database: postgres
rabbitmq:
  host: localhost
  port: 5672
bot:
  vk_token:
  tg_token:
  group_id:
  api: tg
game:
  word_wait_time: 20
  vote_wait_time: 20
  random_start: 1


